Write a function `merge(a, b)` that takes a 2D NumPy numerical array `a` and a 1D NumPy numerical array `b` with the same size (the same number of elements), and:

- Reshapes `b` so that it is a 2D array with the same shape as `a`.
- Returns a new 2D NumPy array that, for each element `i, j`, contains the biggest value between `a[i, j]` and `b[i, j]`, as floats.

In [8]:
import numpy as np
def merge(a,b):
    a = a.astype(float)
    b = np.reshape(b, a.shape).astype(float)
    return np.where(a > b, a, b)

In [9]:
print(merge(np.array([[0,20,4],[7,1,3]]),np.array([0,1,2,3,4,5])))

[[ 0. 20.  4.]
 [ 7.  4.  5.]]


Demeaning is the process in which the mean of a group of data is subtracted from any element of the group. In such a way, the mean of the transformed data is zero. 

Example: demeaning [7, 5] transforms the data into [1, -1].

Using NumPy features, write a function `demean(a)` that takes a 2D array and returns a new 2D array with the same shape, where all columns have been demeaned, i.e., the mean of each column of the result array is equal to 0.

In [12]:
def demean(a):
    return a - a.mean(axis=0)

In [13]:
print(demean(np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])))

[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]


Write a function `colsum(a)` which, given a 2D NumPy array `a` with shape `(n, p)` (with `p >= 2`), returns a new array with shape `(1, 2)` where:

- The first element is the sum of all the elements in the even columns (0, 2, 4, ...).
- The second element is the sum of all the elements in the odd columns (1, 3, 5, ...).

In [ ]:
def colsum(a):
    even_sum = a[:, ::2].sum()
    odd_sum = a[:, 1::2].sum()
    return np.array([[even_sum, odd_sum]])

Write a function `count_common(a, b)` that, given two NumPy 2D arrays `a` and `b` with the same shape (suppose without checking), counts how many common elements (i.e., elements with the same value AND the same position) there are in `a` and `b`.

Elements of the arrays can have an arbitrary type.

In [16]:
import numpy as np

def count_common(a,b):
    #begin student code
    return np.sum(a == b)

In [17]:
print(count_common(np.array([[1,3,8],
              [4,5,2],
              [3,2,9]]),np.array([[2,3,7],
              [4,5,9],
              [6,6,6]])))

3


Write a function `checkerboard(m)` that creates and returns an `m x m` 2D NumPy array filled with a checkerboard pattern (alternating 0s and 1s - see examples) of integers. The function must work for every `m >= 0`.

Tips: either create arrays filled with 0s and then modify them, or use the `fromfunction` creation.

In [ ]:
def checkerboard(m):
    return np.indices((m, m)).sum(axis=0) % 2

In [21]:
checkerboard(5)

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [32]:
def zeroones(p, q):
    new = np.zeros((p, q))
    mask = np.arange(1,(p-2)*(q-2)+1).reshape(p-2, q-2)
    new[1:-1, 1:-1] = mask
    return new

In [33]:
print(zeroones(10,3))


[[0. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]
 [0. 3. 0.]
 [0. 4. 0.]
 [0. 5. 0.]
 [0. 6. 0.]
 [0. 7. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]


In [36]:
def zerocolumns(a):
    return a[:, np.logical_not(np.any(a == 0, axis=0))]

In [37]:
print(zerocolumns(np.array([[1,2,0],[3,1,1],[3,3,0]])))


[[1 2]
 [3 1]
 [3 3]]


In [38]:
#do not insert print or tests
import numpy as np
def arraydistance(p, q):
    result = np.fromfunction(lambda i, j: np.sqrt(i**2+j**2), (p, q))
    return result

In [39]:
print(arraydistance(0,0))
print(arraydistance(3,3))


[]
[[0.         1.         2.        ]
 [1.         1.41421356 2.23606798]
 [2.         2.23606798 2.82842712]]
