In [4]:
#do not insert print or tests

def foo(S):
    track = {}
    for item in S:
        if item not in track.keys():
            track[item] = 1
        else:
            track[item] += 1
    new_track = {v: k for k, v in track.items()}
    result_list = []
    list_frequencies = list(new_track.keys())
    list_frequencies.sort()
    for frequency in list_frequencies:
        result_list.append(new_track[frequency])
    return result_list
    

In [5]:
test = {1: 1, 2: 2, 3: 4}

In [6]:
print(foo([1,2,2,3,3,3,3]))


[1, 2, 3]


In [7]:
S = [1,2,1,1,2,3]
track = {}
for item in S:
    if item not in track.keys():
        track[item] = 1
track

{1: 1, 2: 1, 3: 1}

In [8]:
print(foo([1,2,2,3,3,3,3]))


[1, 2, 3]


In [9]:
print(foo([1,2,1,1,2,3]))


[3, 2, 1]


In [11]:
def sum_one(L, index):
    for i in range(index+1, len(L)):
        L[i] += 1
def is_fair(L):
    for index in range(len(L)-1):
        if L[index+1]==L[index] + 1:
            return False, index
    return True, -1
def fair(L):
    new_L = L
    fair_bool, index = is_fair(new_L)
    first_fair = fair_bool
    while not fair_bool:
        sum_one(L, index)
        fair_bool, index = is_fair(L)
    return first_fair, L

In [12]:
is_fair([1, 3, 7, 10, 12])

(True, -1)

In [13]:
X=[1,2,6,9,10]
idX=id(X)
FX=fair(X)
print(FX, id(FX[1])==idX)

(False, [1, 3, 7, 10, 12]) True


In [18]:
class B:
    def __init__(self, value):
        self.value = value
    def __mul__(self, other):
        return - self.value*other.value
    
        
class A:
    def __init__(self, value):
        self.value = value
    def __mul__(self, other):
        return self.value * other.value

In [19]:
print(A(3)*B(5))
print(B(3)*A(5))


15
-15


In [29]:
def exhaustgen(G):
    iterator = iter(G)
    while True:
        try:
            next(iterator)
        except StopIteration:
            break


In [30]:
exhaustgen(i for i in range(4))

In [31]:
exhaustgen(print(i) for i in range(4))

0
1
2
3


In [33]:
D = {1:2, 2:3}
LL=sorted(zip(D.values(),D.keys()))
LL

[(2, 1), (3, 2)]

In [36]:
x = (i for i in range(4))
iterator = iter(x)

In [37]:
for i in range(8):
    print(next(iterator))

0
1
2
3


StopIteration: 

In [60]:
def merge(L1,L2):
    index_1 = 0
    index_2 = 0
    while index_2 < len(L2):
        if index_1 < len(L1) and L1[index_1]< L2[index_2]:
            index_1 +=1
        else:
            L1.insert(index_1, L2[index_2])
            index_1 += 1
            index_2 += 1
    return L1

In [61]:
print(merge([1,3,5], [0,2,4,6,8,10]))

[0, 1, 2, 3, 4, 5, 6, 8, 10]


In [59]:
def merge(L1, L2):
    index_L1 = 0
    index_L2 = 0
    while index_L2 < len(L2):
        if index_L1 < len(L1) and L1[index_L1] < L2[index_L2]:
            index_L1 += 1
        else:
            L1.insert(index_L1, L2[index_L2])
            index_L1 += 1
            index_L2 += 1
    return L1

print(merge([1, 3, 5], [0, 2, 4, 6, 8, 10]))


[0, 1, 2, 3, 4, 5, 6, 8, 10]


In [ ]:
def merge(L1, L2):
    index_L1 = 0
    index_L2 = 0
    while index_L2 < len(L2):
        if index_L1 < len(L1) and L1[index_L1] < L2[index_L2]:
            index_L1 += 1
        else:
            L1.insert(index_L1, L2[index_L2])
            index_L1 += 1
            index_L2 += 1
    return L1

print(merge([1, 3, 5], [0, 2, 4, 6, 8, 10]))


In [75]:
class A:
   def __init__(self,x):
     self.xx=x
class B(A):
    #your definitions here
    def __init__(self, n1, n2):
        super().__init__(n1)
        self.yy = n2
    def __str__(self):
        return f"{self.xx+self.yy}"

In [76]:
b=B(10,20)
print(b) 


30


In [83]:
import numpy as np

def neg(A):
    return np.where(A < 0, 0, -A)


In [84]:
A =  np.array([[1,-2,3],
                  [-4,5,-6],
                  [7,8,0]])
print(neg(A))

[[-1  0 -3]
 [ 0 -5  0]
 [-7 -8  0]]
